version: 2

models:
  - name: mart_customer_orders
    description: Marketing-focused customer mart with order metrics and segmentation.
    columns:
      - name: customer_id
        description: Primary key for the customer.
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name.
      - name: last_name
        description: Customer's last name.
      - name: full_name
        description: Customer's full name (first + last).
      - name: email
        description: Customer's email address.
        tests:
          - not_null
      - name: customer_created_at
        description: Timestamp when the customer account was created.
      - name: order_count
        description: Total number of orders placed by the customer.
      - name: first_order_date
        description: Date of customer's first order.
      - name: most_recent_order_date
        description: Date of customer's most recent order.
      - name: days_since_last_order
        description: Number of days since the customer's most recent order.
      - name: customer_lifetime_days
        description: Total number of days since the customer was created.
      - name: total_spend
        description: Total amount spent by the customer.
      - name: total_items_purchased
        description: Total number of items purchased by the customer.
      - name: average_order_value
        description: Average order value for the customer.
      - name: total_profit_generated
        description: Total profit generated by the customer.
      - name: customer_segment
        description: Customer segment based on order frequency and recency.
        tests:
          - accepted_values:
              values: ['New Customer', 'Active Repeat Customer', 'Lapsed Repeat Customer', 'Unknown']
      - name: customer_value_tier
        description: Customer value tier based on total spend.
        tests:
          - accepted_values:
              values: ['Low Value', 'Medium Value', 'High Value', 'Unknown']
