version: 2

models:
  - name: int_customer_orders
    description: Intermediate model joining customer and order data.
    columns:
      - name: customer_id
        description: Primary key of the customers table.
        tests:
          - not_null
      - name: first_name
        description: Customer's first name.
      - name: last_name
        description: Customer's last name.
      - name: email
        description: Customer's email address.
      - name: order_id
        description: Primary key of the orders table.
      - name: order_date
        description: Date when the order was placed.
      - name: status
        description: Current status of the order.
      - name: total_amount
        description: Total order amount in dollars.
      - name: shipping_amount
        description: Shipping cost in dollars.
      - name: tax_amount
        description: Tax amount in dollars.

  - name: int_order_items_products
    description: Intermediate model joining order items with product data.
    columns:
      - name: order_item_id
        description: Primary key of the order_items table.
        tests:
          - unique
          - not_null
      - name: order_id
        description: Foreign key to the orders table.
        tests:
          - not_null
      - name: product_id
        description: Foreign key to the products table.
        tests:
          - not_null
      - name: product_name
        description: Name of the product.
      - name: product_category
        description: Category of the product.
      - name: quantity
        description: Number of items ordered.
      - name: unit_price
        description: Price per unit in dollars.
      - name: item_total
        description: Total price for the line item.
      - name: unit_cost
        description: Cost per unit in dollars.
      - name: item_cost
        description: Total cost for the line item.
      - name: item_profit
        description: Profit for the line item (item_total - item_cost).
      - name: item_profit_margin
        description: Profit margin percentage for the line item.
