name: 'ecommerce'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ecommerce'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configure on-run-start hooks for dbt_artifacts
on-run-start:
  - "{{ dbt_artifacts.upload_dbt_artifacts(results=none) }}"

# Configure on-run-end hooks for dbt_artifacts
on-run-end:
  - "{{ dbt_artifacts.upload_dbt_artifacts(results=results) }}"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  ecommerce:
    # Config indicated by + and applies to all files under models/
    +materialized: view
    
    staging:
      +materialized: view
      +schema: staging
    
    intermediate:
      +materialized: view
      +schema: intermediate
    
    marts:
      +materialized: table
      +schema: marts
      
      core:
        +tags: ['core']
      
      marketing:
        +tags: ['marketing']
  
  # dbt_artifacts configuration
  dbt_artifacts:
    +schema: artifacts
    +materialized: table
    staging:
      +schema: artifacts_staging
      +materialized: view

vars:
  'dbt_date:time_zone': 'America/Los_Angeles'
  # dbt_artifacts vars
  dbt_artifacts_database: "{{ target.database }}"
  dbt_artifacts_schema: "{{ target.schema }}_artifacts"
