version: 2

models:
  - name: dim_customers
    description: Customer dimension table with order summary metrics.
    columns:
      - name: customer_id
        description: Primary key for the customer dimension.
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name.
      - name: last_name
        description: Customer's last name.
      - name: full_name
        description: Customer's full name (first + last).
      - name: email
        description: Customer's email address.
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: Date of customer's first order.
      - name: most_recent_order_date
        description: Date of customer's most recent order.
      - name: number_of_orders
        description: Total number of orders placed by the customer.
      - name: is_repeat_customer
        description: Flag indicating if the customer has placed more than one order.
      - name: lifetime_value
        description: Total lifetime value of the customer in dollars.
      - name: created_at
        description: Timestamp when the customer account was created.
      - name: updated_at
        description: Timestamp when the customer account was last updated.

  - name: dim_products
    description: Product dimension table with sales metrics.
    columns:
      - name: product_id
        description: Primary key for the product dimension.
        tests:
          - unique
          - not_null
      - name: name
        description: Product name.
        tests:
          - not_null
      - name: description
        description: Product description.
      - name: category
        description: Product category.
      - name: price
        description: Current product price in dollars.
      - name: cost
        description: Current product cost in dollars.
      - name: margin
        description: Current product margin (price - cost).
      - name: margin_percent
        description: Current product margin percentage.
      - name: inventory_quantity
        description: Current inventory level.
      - name: total_quantity_ordered
        description: Total quantity of the product ordered across all orders.
      - name: total_revenue
        description: Total revenue generated by the product.
      - name: total_profit
        description: Total profit generated by the product.
      - name: created_at
        description: Timestamp when the product was created.
      - name: updated_at
        description: Timestamp when the product was last updated.

  - name: dim_dates
    description: Date dimension table for time-based analysis.
    columns:
      - name: date_day
        description: Primary key for the date dimension.
        tests:
          - unique
          - not_null
      - name: day_of_week
        description: Day of week (0-6, 0 being Sunday).
      - name: day_of_week_name
        description: Name of the day of week (Sunday, Monday, etc.).
      - name: day_of_month
        description: Day of month (1-31).
      - name: day_of_year
        description: Day of year (1-366).
      - name: week_of_year
        description: Week of year (1-53).
      - name: month_number
        description: Month number (1-12).
      - name: month_name
        description: Month name (January, February, etc.).
      - name: quarter
        description: Quarter (1-4).
      - name: year
        description: Year (e.g., 2023).
      - name: is_weekend
        description: Boolean flag indicating if the date is a weekend.
      - name: is_end_of_month
        description: Boolean flag indicating if the date is the last day of the month.

  - name: fct_orders
    description: Order fact table with order details and metrics.
    columns:
      - name: order_id
        description: Primary key for the order fact.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to dim_customers.
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: order_date
        description: Date when the order was placed.
        tests:
          - not_null
      - name: order_year
        description: Year of the order.
      - name: order_month
        description: Month of the order.
      - name: order_quarter
        description: Quarter of the order.
      - name: order_day_of_week
        description: Day of week of the order.
      - name: status
        description: Current status of the order.
      - name: total_items
        description: Total number of items in the order.
      - name: total_amount
        description: Total order amount including tax and shipping.
      - name: shipping_amount
        description: Shipping cost.
      - name: tax_amount
        description: Tax amount.
      - name: items_total_amount
        description: Sum of all item totals.
      - name: items_total_cost
        description: Sum of all item costs.
      - name: items_total_profit
        description: Total profit from the order (items_total_amount - items_total_cost).
      - name: created_at
        description: Timestamp when the order was created.
      - name: updated_at
        description: Timestamp when the order was last updated.
